version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  open-pull-requests-limit: 10
  schedule:
    interval: daily
  cooldown:
    default-days: 7
- package-ecosystem: nuget
  directory: /
  open-pull-requests-limit: 10
  schedule:
    interval: daily
  groups:
    MicrosoftExtensions:
      patterns:
      - Microsoft.Extensions.*
    coverlet:
      patterns:
      - coverlet.*
  cooldown:
    default-days: 7
- package-ecosystem: dotnet-sdk
  directory: /
  schedule:
    interval: daily
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
  cooldown:
    default-days: 7
- package-ecosystem: devcontainers
  directory: /
  open-pull-requests-limit: 10
  schedule:
    interval: daily
  cooldown:
    default-days: 7
