manifest: true
primaryBranch: main
handleGHRelease: true
branches:
  - branch: support/v1
    manifest: true
    handleGHRelease: true
  - branch: support/v2
    manifest: true
    handleGHRelease: true