namespace Microsoft.OpenApi.Diff.Enums
{
    public enum ChangedElementTypeEnum
    {
        OpenApi,
        Operation,
        RequestBody,
        Path,
        Content,
        Response,
        Request,
        Parameter,
        Schema,
        OneOf,
        AnyOf,
        AllOf,
        Header,
        SecurityRequirement,
        SecurityScheme,
        SecuritySchemeScope,
        AuthFlow,
        Metadata,
        MediaType,
        WriteOnly,
        ReadOnly,
        MaxLength,
        Required,
        Extension,
        Enum
    }
}
