//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.OpenApi.Reader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SRResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SRResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.OpenApi.Readers.Properties.SRResource", typeof(SRResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; is null, empty or consists only of white-space..
        /// </summary>
        internal static string ArgumentNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ArgumentNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Cannot resolve remote references automatically in a syncronous call.&quot;.
        /// </summary>
        internal static string CannotResolveRemoteReferencesSynchronously {
            get {
                return ResourceManager.GetString("CannotResolveRemoteReferencesSynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON pointer &apos;{0}&apos; does not point to an object in the document..
        /// </summary>
        internal static string JsonPointerCannotBeResolved {
            get {
                return ResourceManager.GetString("JsonPointerCannotBeResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented to find referenced element from external resource..
        /// </summary>
        internal static string LoadReferencedObjectFromExternalNotImplmented {
            get {
                return ResourceManager.GetString("LoadReferencedObjectFromExternalNotImplmented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference string &apos;{0}&apos; has invalid format..
        /// </summary>
        internal static string ReferenceHasInvalidFormat {
            get {
                return ResourceManager.GetString("ReferenceHasInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type of $ref &apos;{0}&apos; at &apos;{1}&apos; for V2 document..
        /// </summary>
        internal static string ReferenceV2HasInvalidValue {
            get {
                return ResourceManager.GetString("ReferenceV2HasInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type of $ref &apos;{0}&apos; at &apos;{1}&apos; for V3 document..
        /// </summary>
        internal static string ReferenceV3HasInvalidValue {
            get {
                return ResourceManager.GetString("ReferenceV3HasInvalidValue", resourceCulture);
            }
        }
    }
}
